### ISSUE TITLE
MySQL 초기화 작업 (유저 권한 관리, 테이블 초기화)

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-infra#28]
# Description

아래 Todo 작업이 필요합니다.
- 다만 아래 작업을 실제로 Terraform을 통해서 진행할지, DBA이 Workbench 등 툴을 통해서 진행할지 정해지지 않았습니다.
- 하지만 최대한 자동화/명시적으로정의 가능한 부분은 시도해봐야 한다고 생각합니다.
- 그런 의미에서 Terraform을 통한 방법을 조사하고, 고려할 예정입니다.

## 사용자 정의

해당 권한에 대한 내용은 예상해서 작성했습니다. 자료 조사 후 재정의 부탁드립니다. 
- DBA: Table 생성, 삭제 등 최상위 권한 소유
- Backend-Developer-prod: SELECT 권한 소유
- Backend-Developer-dev : CRUD 권한 소유
- Application: CRUD 권한 소유 

# To do

### User
- [x] User 권한에 대한 Best Practice 자료 찾기
- [x] Terraform을 통한 방법 조사 
- [x] 해당 작업 완료 후 Root 계정 사용 금지화 

### Table Init
- [x] Terraform을 통한 Table Init 방법 조사 

# Test Checklist

**Comment by hihahayoung** [comment]
공식문서:
https://dev.mysql.com/doc/mysql-monitor/8.0/en/mem-acl-best-hybrid-ref.html

참고자료:
https://www.prisma.io/dataguide/mysql/authentication-and-authorization/role-management

terraform:
https://www.devopsschool.com/slide/storage/training_logos/345_fRQFX0dAAO2WhuVJ8JWaCFQeaH1865DW/logo_345_1650020360_mysql.pdf

**Comment by hihahayoung** [comment]
이번 프로젝트는 DB가 dev와 prod로 구분되어 있지 않기 때문에 굳이 Developer role을 나눌 필요가 없어 보입니다. 3개로 나누면 충분할 것 같네요.

- DBA: Table 생성, 삭제 등 최상위 권한 소유
- Developer: SELECT 권한 소유
- Application: CRUD 권한 소유

**Comment by junha-ahn** [comment]
관련 글
- https://stackoverflow.com/questions/73735108/automate-aws-rds-user-management
- https://stackoverflow.com/questions/47997844/terraform-sql-create-users-from-variable
- https://stackoverflow.com/questions/58269123/best-practice-how-to-use-terraform-to-create-custom-mysql-rds-user-via-ci (DB Migration Tool 이란?)


`automate db user management` 키워드로 검색하니까 자료들이 나오네요! 

참고해서 가장 좋은 방법을 도입해주셨으면 합니다

**Comment by hihahayoung** [comment]
## SQL 주입 하기

1. user role 생성
2. user role에 permission grant
3. user 생성
4. user에 user role 부여

### 루트 로그인
1. 각 user 패스워드 생성
2. 전달
3. root logout

**Comment by hihahayoung** [comment]
```
CREATE ROLE 'manager', 'developer', 'application';
GRANT ALL ON ticketingdb.* TO 'manager';
GRANT SELECT ON ticketingdb.* TO 'developer';
GRANT INSERT, UPDATE, SELECT, DELETE ON ticketingdb.* TO 'application';

CREATE USER 'manager'@'10.0.65.157' IDENTIFIED BY 'manager';   // Bastion Private IP Address
CREATE USER 'developer1'@'10.0.65.157' IDENTIFIED BY 'read_developer1';
CREATE USER 'developer2'@'10.0.65.157' IDENTIFIED BY 'read_developer2';
CREATE USER 'developer3'@'10.0.65.157' IDENTIFIED BY 'read_developer3';
CREATE USER 'application'@'10.0.65.157' IDENTIFIED BY 'application';

GRANT 'manager' TO 'manager'@'10.0.65.157';
GRANT 'developer' TO 'developer1'@'localhost', 'developer2'@'localhost',  'developer3'@'localhost';
GRANT 'application' TO 'application'@'10.0.65.157';

SHOW GRANTS FOR manager;
SHOW GRANTS FOR manager@10.0.65.157;
```

참고:
https://dev.mysql.com/doc/refman/8.0/en/roles.html
https://advancedweb.hu/how-to-run-sql-scripts-against-the-rds-data-api-with-terraform/

*Terraform으로 넣는 방법이 있지만 별로 깔끔하지 않은 것 같네요. 그냥 손으로 치는 게 나을 수도 있을 것 같다는 생각...

**Comment by junha-ahn** [comment]
아직 Desired state 를 관리하는 방법이 없나보네요. (배포로 치면 git ops같은)
- 수정을 생각하면 결국 의미가 딱히없어지네요. (매번 recreate할 것도 아니고)

DB는 관리자가 직접 관리하고, Inital SQL문을 Git에 저장하는것 정도로 이슈 close하겠습니다
