### ISSUE TITLE
Spring App 모니터링 (Spring Boot Actuator)

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-infra#44]
# Description

[Backend App](https://github.com/f-lab-clone/helm-repository/blob/main/incubator/ticketing-chart/templates/backend-deployment.yaml) 모니터링 (Spring Boot Actuator + Grafana 키워드 등 학습) 
- Terraform 또는 [Helm Repository](https://github.com/f-lab-clone/helm-repository/tree/main/incubator/ticketing-chart/templates) 이용

# To do

# Test Checklist
- [ ] Grafana에 Spring App 관련 대시보드 설치

**Comment by hihahayoung** [comment]
아마 spring boot의 gardle 설정을 추가하고... helm repository에 yaml 파일로 배포하고 .. 험난한 과정을 겪을 수 있다.

**Comment by junha-ahn** [comment]
Pod 여러개일때는 어떻게 되는건지 궁금하네요. (일단 제가 요번주 안에 Pod 2개로 변경해보겠습니다)
