### ISSUE TITLE
대시보드 고도화

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-infra#66]
# Description

[성능테스트](https://github.com/f-lab-clone/ticketing-backend/issues/92)에 따른 대시보드 고도화

`Latency` 파악을 위해 모든 대시보드에 항목 추가

### 기타

아래와 같은 키워드로 Computing 자원 대시보드를 잘 찾아야...
- [그라파나 대시보드 추천](https://jerryljh.medium.com/grafana-dashboard-%EC%B6%94%EC%B2%9C-41744edcc7f9)

## Data Empty
- 현재 대시보드의 전반적인 `data empty` 문제는 **모두 짧은 테스트 시간으로 인해 발생하는 데이터 부족이 원인** (`rate` 그래프 등)
- 따라서 두가지 개선 
  - Dashboard 테스트를 위해 Load Test 도입 (2~3분)
  - **Scrape Interval (그라파나, 프로메테우스 모두) `15s` 로 조정** 

# To do
- [x] Latency 파악을 위한 대시보드 항목 추가 
    1. MySQL: 실패
    2. ~~Spring App~~
    3. ~~Nginx~~
    4. ~~K6~~

이후 작업
- Spring 대시보드 개선 ([링크](https://github.com/f-lab-clone/ticketing-infra/issues/66#issuecomment-1742563358))
- Spring `users/signin` 엔드포인트 unknown 문제 해결 ([링크](https://github.com/f-lab-clone/ticketing-backend/issues/95#issuecomment-1742109526))
- 컴퓨팅 자원 대시보드 조사 (검색)

# Test Checklist

테스트 시나리오 1
- [x] Average Load Test 구현 (3분)
- [x] 대시보드: Latency 확인 가능

테스트 시나리오 2
- [x] Spike Test 구현 (1분)
- [x] 대시보드: Latency 확인 가능

**Comment by junha-ahn** [comment]
# MySQL Query Response Time 관련

방법
1. `@profile` 옵션 활성화
2. SLOW_QUERY 시간 기준 변경

고려사항
- `src/mysql` 폴더에 해당 옵션 기록

## profile

참고
- https://www.sentinelone.com/blog/how-to-measure-mysql-query-time/

고려사항
- MySQL Exporter 스크랩 가능 여부

## SLOW_QUERY 시간 기준 변경

참고
- [MySQL slow query 를 효율적으로 이용해보자!](http://minsql.com/mysql/MySQL-slow-query-%EB%A5%BC-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%9D%B4%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90/)

**Comment by hihahayoung** [comment]
https://dev.mysql.com/doc/mysql-infoschema-excerpt/5.7/en/information-schema-variables-table.html

**Comment by junha-ahn** [comment]
# Spring Actuator

**Comment by junha-ahn** [comment]
# Nginx 

목적 
- Latency 조회

**Comment by hihahayoung** [comment]
## PromQL 관련 참고

https://hyuuny.tistory.com/220

**Comment by junha-ahn** [comment]
# 문제점

### Spring

![image](https://github.com/f-lab-clone/ticketing-infra/assets/41976906/3369faac-6759-409c-a08e-ea3d0a9a0637)
- 특정 API URL을 `Unknown` 으로 노출

### Nginx

![image](https://github.com/f-lab-clone/ticketing-infra/assets/41976906/0e064932-6a84-47e7-8ae8-fc636672efdc)
- 계산식 문제인지 값이 노출되지 않는 경우가 많다.

**Comment by junha-ahn** [comment]
https://www.alibabacloud.com/blog/observability-%7C-best-practices-for-monitoring-nginx-ingress-gateways-with-prometheus_600349

**Comment by junha-ahn** [comment]
ingress-nginx => nginx exporter 사용법

**Comment by junha-ahn** [comment]
질문글  https://github.com/kubernetes/ingress-nginx/issues/10464

**Comment by junha-ahn** [comment]
현재 문제
- https://stackoverflow.com/questions/54503694/how-to-properly-log-the-path-in-k8s-ingress-nginx-metrics

**Comment by junha-ahn** [comment]
# 스프링 문제

![image](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/b3fdce09-d2da-44fd-bcf2-3b33cb4fe971)

1. `last -1m`으로 대시보드 설정 변경
2. `.../events`, `/reservations` 조회
3. `/`에 정보만 변경된다.

![image](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/b36fc96f-1ba8-4b74-96bd-0332334f4c18)
- 그외 `events/{id}` 나 `users/get_accesss_token` 은 잘 나오는걸 보면... 흠... 뭐가 문제일까...

**접근방법** 
- raw metric 데이터 확인
- 확인 이유: 매트릭을 해석하는 과정에서 문제가 생긴 것인지.. 아닌지...

**지금 가장 중요한건**
1. K6에서 매트릭중에 각 path 별로 p(95) latency가 안나온다
2. spring에서 매트릭중에 **각 path 별로 latency가 구분안된다.**

이러한 것들을 해결해야 성능 테스트/시간체크가 가능하다.

# 매트릭 실제 조회

한번 매트릭을 조회해봤다

```
# HELP http_server_requests_seconds  
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{uri="/actuator/prometheus",} 300.0
http_server_requests_seconds_sum{uri="/actuator/prometheus",} 2.180023624
http_server_requests_seconds_count{uri="/users/access_token_info",} 1.0
http_server_requests_seconds_sum{uri="/users/access_token_info",} 0.005580759
http_server_requests_seconds_count{uri="/events/",} 145.0
http_server_requests_seconds_sum{uri="/events/",} 2.450245069
http_server_requests_seconds_count{uri="/reservations",} 101.0
http_server_requests_seconds_sum{uri="/reservations",} 4.09100655
http_server_requests_seconds_count{uri="/",} 1798.0
http_server_requests_seconds_sum{uri="/",} 4.568047614
http_server_requests_seconds_count{uri="UNKNOWN",} 1.0
http_server_requests_seconds_sum{uri="UNKNOWN",} 0.002718621
http_server_requests_seconds_count{uri="/users/signup",} 161.0
http_server_requests_seconds_sum{uri="/users/signup",} 89.599115841
http_server_requests_seconds_count{uri="UNKNOWN",} 135.0
http_server_requests_seconds_sum{uri="UNKNOWN",} 54.967169598
http_server_requests_seconds_count{uri="UNKNOWN",} 1.0
http_server_requests_seconds_sum{uri="UNKNOWN",} 0.025473794
http_server_requests_seconds_count{uri="NOT_FOUND",} 1.0
http_server_requests_seconds_sum{uri="NOT_FOUND",} 0.037586379
http_server_requests_seconds_count{uri="UNKNOWN",} 13.0
http_server_requests_seconds_sum{uri="UNKNOWN",} 0.092418664
http_server_requests_seconds_count{uri="/events/{id}",} 3.0
http_server_requests_seconds_sum{uri="/events/{id}",} 0.087311747
http_server_requests_seconds_count{uri="/users/access_token_info",} 4.0
http_server_requests_seconds_sum{uri="/users/access_token_info",} 0.020254882
```
## 즉시 새로 고침 후 

```
# HELP http_server_requests_seconds  
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{uri="UNKNOWN",} 1.0
http_server_requests_seconds_sum{uri="UNKNOWN",} 0.003554286
http_server_requests_seconds_count{uri="/users/signup",} 134.0
http_server_requests_seconds_sum{uri="/users/signup",} 64.053013834
http_server_requests_seconds_count{uri="/actuator/prometheus",} 302.0
http_server_requests_seconds_sum{uri="/actuator/prometheus",} 1.979310226
http_server_requests_seconds_count{uri="UNKNOWN",} 162.0
http_server_requests_seconds_sum{uri="UNKNOWN",} 66.806344243
http_server_requests_seconds_count{uri="NOT_FOUND",} 4.0
http_server_requests_seconds_sum{uri="NOT_FOUND",} 0.055016017
http_server_requests_seconds_count{uri="/reservations",} 121.0
http_server_requests_seconds_sum{uri="/reservations",} 4.911549812
http_server_requests_seconds_count{uri="/events/",} 126.0
http_server_requests_seconds_sum{uri="/events/",} 1.416426921
http_server_requests_seconds_count{error="none",exception="none",method="GET",outcome="SERVER_ERROR",status="500",uri="UNKNOWN",} 14.0
http_server_requests_seconds_sum{error="none",exception="none",method="GET",outcome="SERVER_ERROR",status="500",uri="UNKNOWN",} 0.033144101
http_server_requests_seconds_count{uri="/events/{id}",} 2.0
http_server_requests_seconds_sum{uri="/events/{id}",} 0.039381977
http_server_requests_seconds_count{uri="/",} 1797.0
http_server_requests_seconds_sum{uri="/",} 4.413052742
http_server_requests_seconds_count{uri="/users/access_token_info",} 2.0
http_server_requests_seconds_sum{uri="/users/access_token_info",} 0.008590401
```

## 생각

그냥 다른건 요청안하고 매트릭 페이지만 새로고침했는데 `users/access_token_info` 등에 대한 매트릭 값이 변하는걸 봐서는... 음 일단 매트릭정보가 어떻게 나타나는지에 대한 매커니즘을 이해해야.

- 근데 spring에서 path 별로 구분해서 데이터를 주는데 왜 `/` 데이터만 그래프에서 변하지

## 이해하기 위해

관련 매트릭 질문: https://stackoverflow.com/questions/67964176/springboot-observability-on-max-count-sum-metrics

spring actuator latency 매트릭을 직접 구성하는 방법 https://medium.com/jongho-developer/spring-boot-meaningful-percentile-api-latency-metrics-58d1a78d91fb

https://lollaziest.tistory.com/186 를 보면 tomcat 정보를 on하는 방법 설명

**Comment by junha-ahn** [comment]
# K6

![Uploading image.png…]()

**Comment by junha-ahn** [comment]
## 매트릭에 관해서 

출처 (더 자세한 정보는 해당 출처로)
- https://stackoverflow.com/questions/67964176/springboot-observability-on-max-count-sum-metrics
- [Prometheus rate() 연산의 실행 원리](https://velog.io/@skynet/Prometheus-rate-%EC%97%B0%EC%82%B0%EC%9D%98-%EC%8B%A4%ED%96%89-%EC%9B%90%EB%A6%AC)

## Count / Sum


`count`와 `sum`은 일반적으로 평균을 계산할때 사용됩니다.
- `count`는 횟수를 누적한다
- `sum`은 무언가의 총 가치를 보유하고 있다.

```
http_server_requests_seconds_sum 10 
http_server_requests_seconds_count 5 
```
- 위의 예를 들어보면, HTTP 요청이 5개 있었고, 총 지속시간은 10초였다
- `sum / count`로 나누면 평균 요청시간은 2초이다.
- average request duration (=average latency) 라는 유용한 패널을 만들 수 있다.

## Rate

시계열 데이터 중에는 그 자체의 값보다 변화량이 더 중요한 경우가 있다

> 예를 들어 리눅스의 cpu 사용량은 어떤 프로세스가 실행되는 동안 cpu를 점유한 시간으로 정의된다. cpu 점유 시간 자체는 프로세스가 종료되기 전까지 계속 증가할 수 밖에 없기 때문에, 단순히 cpu 점유 시간이 많은 프로세스를 점검하는 것보다 cpu 점유 시간이 최근 빠르게 늘어난 프로세스를 점검하는 것이 시스템 관리 측면에서 훨씬 도움이 된다.

rate() 연산은 지정한 시간 범위 내에 메트릭이 변화한 정도를 보기 위한 연산이다. 특히 **Counter** 타입의 메트릭과 자주 사용되는데, 끊임없이 증가하기만 하는 raw data를 볼 이유가 없기 때문이다. Counter 타입 메트릭의 대표적인 예로 앞서 소개한 cpu 사용 시간이 있다.

## rate() 계산 방법

rate는 range vector의 **처음과 끝의 샘플**을 이용해 '초당 평균 변화율'을 계산한다. t1과 t2 사이의 초당 평균 변화율은 `(sample(t2) - sample(t1)) / (t2 - t1)` 을 통해 계산한다. 당연히 range vector 내에 **최소한 두 개의 샘플**이 존재해야 한다 

> **너무 짧은 시간**(1분)의 테스트인 Spike Test가 대부분의 **그래프를 그려내지 못하는 이유**도 다음 이유때문이였다.

예를 들어 1분 동안의 rate를 계산한다고 가정하자. 데이터는 15초마다 수집 되었고 값은 `[10, 20, 50, 80]` 이다. rate는 첫 샘플인 10과 마지막 샘플인 80을 통해 계산한다. 앞서 소개한 공식대로 계산하면`70 / 60 = 1.166` 이 된다.

![image](https://github.com/f-lab-clone/ticketing-infra/assets/41976906/0bf4176f-2c57-4703-abbc-3770a3666d44)

물론 위의 상황에서 첫 샘플과 마지막 샘플을 이용해 rate를 구할수도 있다. **그러나 이렇게 되면 1분 간의 평균 변화율이라는 쿼리의 의도와 맞지 않게 된다.** Prometheus는 실제 점 대신 **가상의 점을 추측**하여 사용하는 외삽(extrapolation)을 이용한다.

외삽을 하는 방법은 다음과 같다. 우선 첫 샘플과 끝 샘플을 이은 직선을 긋고 기울기를 구한다. 이 기울기가 관측되지 않은 기간에도 유지되었을 것이라고 가정하고, time-range 경계에 가상의 점을 찍는다. 이 가상의 점들끼리 rate() 연산을 해 변화량을 구한다.

![image](https://github.com/f-lab-clone/ticketing-infra/assets/41976906/484cd383-47fb-4728-bae8-003409aadc09)

데이터의 왜곡을 방지하기 위해 시간 범위의 경계와 샘플의 경계가 너무 멀 때는 외삽으로 찍는 점의 범위를 제한한다. 

## Request Count Per Second

```
rate(http_server_requests_seconds_count[5m])
```

1. Prometheus는 지정된 간격(예제에서는 5분)에서 샘플을 가져와 현재 시점(으로 추정되는 값)과 차이를 계산한다
2. 얻은 값을 seconds in the interval (5m)으로 나눈다

구간이 짧으면 그래프가 톱처럼 보이고, 구간이 길면 선이 더 매끄럽고 변화를 표시하는 속도가 느려진다. 

## Average Request Duration

 ```
http_server_requests_seconds_sum / http_server_requests_seconds_count
```

하지만 그래프에서는 직선만 보일 가능성이 높습니다. 이는 해당 측정항목값이 시간이 지남에 따라 너무 커지고, 이 쿼리가 차이를 표시하려면 정말 급격한 변화가 발생해야 하기 때문. 이러한 특성으로 데이터 간격 샘플에 대한 평균을 계산하는게 더 좋다. [increase()](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase)  함수를 사용해서 inteval 동안 매트릭이 어떻게 변화했는지에 대해 '근사값'을 얻을 수 있다.

```
increase(http_server_requests_seconds_sum[5m]) / increase(http_server_requests_seconds_count[5m]) 
```


## Scrape Interval 조절

출처
- https://stackoverflow.com/questions/66549609/what-is-the-minimum-scrape-interval-in-prometheus
- https://www.robustperception.io/keep-it-simple-scrape_interval-id/
- https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/

요약
- 1초 등의 너무 짧은 시간은 의미가 없다 (네트워크 지연 등)
- 모든 서비스에 단일한 scrape interval을 사용해라

그렇다면 나는 어느정도의 inteval을 사용해야할까?

> 일반적으로 Grafana와 Promethus 모두 Scrape Inteval을 `60s` 으로 설정하는 것이 좋습니다.
[from](https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/optimize-scrape-interval/)

그러나 1분 미만의 Spike Test가 목적임으로 inteval을 `15s`으로 설정하자.

**Comment by junha-ahn** [comment]
# 대시보드 선정

## 테스트
1. Load Test 진행 (3m) 후 대시보드 비교
2. Spike Test 진행 (30s) 후 대시보드 비교
3. k6 `native histogram` 플러그인에 따라 Load/Spike Test 후 대시보드 비교

## 대시보드 종류

### K6
- ~~k6 Prometheus: 19665~~
- k6 Prometheus (Native Histograms): 18030

### Nginx
- NGINX Ingress controller: 9614
- Request Handling Performance:9614
- ~~Kubernetes Nginx Ingress Prometheus NextGen: 14314~~

### Spring
- Spring Boot Statistics: [12464](https://grafana.com/grafana/dashboards/12464-spring-boot-statistics/)
- Spring HTTP Example: [17360](https://grafana.com/grafana/dashboards/17360-spring-http-example/) (스택오버플로우 예시)

개선사항
- [ ] JETTY => TOMCAT
- [ ] DB 매트릭 개선

참고
- [spring actuator latency 매트릭을 구성하는 방법](https://medium.com/jongho-developer/spring-boot-meaningful-percentile-api-latency-metrics-58d1a78d91fb) (추가 metric 설정을 on)
- https://lollaziest.tistory.com/186  (tomcat metric을 on하는 방법 설명)

**Comment by junha-ahn** [comment]
# MySQL 

목적
- Latency 조회

고려사항
- `src/mysql` 폴더 또는 `src/terrafrom/mysql` 파일에 해당 옵션 기록

결과
- **query response time 조회 실패** 

참고
- https://sysdig.com/blog/mysql-monitoring/


## info_schema_query_response_time

https://github.com/prometheus/mysqld_exporter/blob/main/collector/info_schema_query_response_time.go


```
Scrape `information_schema.query_response_time*` tables.
```

고려사항
- MySQL `information_schema.query_response_time` 테이블 활성화 가능 여부


**MYSQL 8.x 버전에 해당 테이블 없음**으로 실패
- https://forums.percona.com/t/the-file-query-response-time-so-does-not-exists-into-mysql-version-ver-8-0-19/7977/3
- https://forums.percona.com/t/query-response-time-details-dashboard/14124
- 관련 질문글 : https://github.com/prometheus/mysqld_exporter/issues/771 (답변: MySQL은 지원하지 않는다)

## SLOW_QUERY 시간 기준 변경

참고
- [MySQL slow query 를 효율적으로 이용해보자!](http://minsql.com/mysql/MySQL-slow-query-%EB%A5%BC-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%9D%B4%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90/)

장점
- Prometheus 및 Mysql-exporter 설정 **변경 필요 없음**

결과
- 0초 이상 발생한 Query Count 개수를 가지고 올 수 는 있지만, time을 가지고 올 수 는 없음으로 **실패**

## profile

참고
- https://www.sentinelone.com/blog/how-to-measure-mysql-query-time/

고려사항
- MySQL Exporter 스크랩 가능 여부

----

<img width="805" alt="image" src="https://github.com/f-lab-clone/ticketing-infra/assets/41976906/031647f8-cbe8-4dc6-9f6e-4fbf8d9b68af">
> Prometheus Slack Channel

**Comment by junha-ahn** [comment]
# Nginx 

목적 
- Latency 조회



참고 
- [공식 대시보드](https://github.com/kubernetes/ingress-nginx/tree/main/deploy/grafana/dashboards)

## Dashboard not Working

모든 nginx **대시보드 데이터 출력에 문제가 있는 상태**

이슈 등록
- https://github.com/kubernetes/ingress-nginx/issues/10464 (해결)
- https://github.com/kubernetes/ingress-nginx/issues/10465

다른 접근 방법
- Nginx Exporter를 사용해서 Dashboard 구성
- Nginx 삭제 후 ALB 사용 (#62 관련)

기타: `users/signin` 엔드포인트 `unknown` 문제
- https://github.com/f-lab-clone/ticketing-backend/issues/95#issuecomment-1742109526

**Comment by junha-ahn** [comment]
# Spring Actuator

목적
- Latency 조회

## PromQL 참고
- https://hyuuny.tistory.com/220
- https://www.devkuma.com/docs/prometheus/spring-boot/default-metrics/

## 개선사항
- [ ] JETTY => TOMCAT
- [ ] DB 매트릭 개선
